config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end

  resources :messages, only: [:new, :create]
  resources :chat_rooms


  get 'message/:id/up' => 'messages#up', as: 'up_message'
  get 'message/:id/down' => 'messages#down', as: 'down_message'
  root to: 'chat_rooms#index'
end

app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
  belongs_to :user
end

app/models/message_vote.rb
class MessageVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :message,
           foreign_key: "mailboxer_notifications_id", dependent: :destroy,
           class_name: "Mailboxer::Notification"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter, :google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
                           provider:access_token.provider,
                           email: data["email"],
                           uid: access_token.uid ,
                           password: Devise.friendly_token[0,20],
        )
      end
    end
    end

  def self.find_for_facebook(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
                           provider:access_token.provider,
                           email: data["email"],
                           uid: access_token.uid ,
                           password: Devise.friendly_token[0,20],
        )
      end
    end
  end

  has_many :chat_rooms, dependent: :destroy
  acts_as_messageable
  has_many :message_votes
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found.'
    redirect_back_or root_path
  end

  def redirect_back_or(path)
    redirect_to request.referer || path
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]

  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  enable_sync only: [:create]

  def new
  end

  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
  end

  def up
    message = Mailboxer::Message.find(params[:id])
    message.liked_by current_user

    redirect_to conversation_path(message.conversation.id)
  end

  def down
    message = Mailboxer::Message.find(params[:id])
    message.disliked_by current_user

    redirect_to conversation_path(message.conversation.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size = 30, title = user.email)
    image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>  #{user.email}</option>"
    end
    s.html_safe
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                    data: {confirm: 'Are you sure?'} %>

        <% if conversation.is_unread?(current_user) %>
            <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                        class: 'btn btn-xs btn-info', method: :post %>
        <% end %>
    <% end %>
  </div>


  <p><%= render 'conversations/participant', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participant.html.erb
<% @conversations.each do |conversation| %>
<% end %>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
    <% unless participant == current_user %>
        <%= gravatar_for participant %>
    <% end %>
<% end %>

app/views/conversations/index.html.erb
<p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>

<div class="col-sm-9">
  <% if @box == 'trash' %>
      <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                     data: {confirm: 'Are you sure?'} %></p>
  <% end %>
  <ul class="list-group">
    <%= render partial: 'conversations/conversation', collection: @conversations %>
  </ul>

  <%= will_paginate %>
</div>

app/views/conversations/show.html.erb
<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <%= sync partial: 'message_row', collection: @conversation.receipts_for(current_user) %>
      <%= sync_new partial: 'message_row', resource: Mailboxer::Notification.new %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
    <div class="form-group">
      <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
    </div>
    <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_sync_config %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">-->
  <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>-->

</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Chat4Box', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>

          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Your Conversations', conversations_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to "Sign in with Google", '/auth/google_oauth2' %></li>
          <li><%= link_to 'Facebook', '/auth/facebook' %></li>
    <% end %>
    </ul>
  </div>
</nav>

<div class="container">

  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/messages/new.html.erb
<%= form_tag messages_path, method: :post do %>
    <div class="form-group">
      <%= label_tag 'message[subject]', 'Subject' %>
      <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= label_tag 'message[body]', 'Message' %>
      <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= label_tag 'recipients', 'Choose recipients' %>
      <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control' %>
    </div>

    <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>

app/views/sync/mailboxer/receipts/_message_row.html.erb
<div class="media">
  <% message = receipt.message %>
  <div class="media-left">
    <%= gravatar_for message.sender, 45, message.sender.email %>
  </div>

  <div class="media-body row">
    <div class="col-sm-8">
      <h6 class="media-heading"><%= message.sender.email %>
        says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
      <%= message.body %>
    </div>
    <div class="col-sm-2">
      <%= message.get_likes.size %><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" style="color: #245580"></span>
      <%= message.get_dislikes.size %> <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true" style="color: #b92c28"></span>
    </div>
    <div class="col-sm-2">
      <% if !current_user.voted_for? message %>
          <%= link_to 'Up', up_message_path(message.id), {class: 'btn btn-primary'}%>
          <%= link_to 'Down', down_message_path(message.id), {class: 'btn btn-danger'}%>
      <% elsif current_user.voted_up_on? message %>
          <%= link_to 'Down', down_message_path(message.id), {class: 'btn btn-danger'}%>
      <% else %>
          <%= link_to 'Up', up_message_path(message.id), {class: 'btn btn-primary'}%>
      <% end %>
    </div>
  </div>

</div>

app/views/sync/users/_user_info.html.erb
<button class="btn"><%= user.email %></button>